# Generated by Django 4.0.6 on 2022-09-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_date_birth_customuser_male_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='+', max_length=50, null=True),
        ),
    ]
