# Generated by Django 4.0.6 on 2022-11-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=169, null=True, verbose_name='address'),
        ),
    ]
