# Generated by Django 4.0.6 on 2022-08-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_date_birth_customuser_male'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Date_birth',
            new_name='date_birth',
        ),
    ]
