# Generated by Django 4.0.6 on 2022-11-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='male',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
