# Generated by Django 4.0.6 on 2022-08-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_date_birth_customuser_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_birth',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='male',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
