# Generated by Django 4.0.6 on 2022-11-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_male'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='male',
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('None', 'Не выбрано'), ('man', 'Мужчина'), ('woman', 'Женщина')], max_length=30, null=True),
        ),
    ]
