# Generated by Django 4.0.6 on 2022-11-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customuser_male_customuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.CharField(max_length=150, null=True, verbose_name='points'),
        ),
    ]
