# Generated by Django 4.0.6 on 2022-08-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='male',
            field=models.CharField(choices=[('', ''), ('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], default='1', max_length=30),
        ),
    ]
