# Generated by Django 4.0.6 on 2022-08-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_male'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_birth',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
