# Generated by Django 4.0.6 on 2022-11-27 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=40)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=40)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_house',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.addressinfomodel'),
        ),
    ]
