# Generated by Django 4.0.6 on 2022-08-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_birth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='male',
            field=models.CharField(blank=True, choices=[('', ''), ('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], default='1', max_length=30, null=True),
        ),
    ]
