# Generated by Django 4.0.6 on 2022-11-28 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_addressinfomodel_customuser_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_coordinates',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_house',
        ),
        migrations.CreateModel(
            name='AdressInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=169, null=True, verbose_name='address')),
                ('is_house', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('address_coordinates', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.addressinfomodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
