# Generated by Django 4.0.6 on 2022-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_customuser_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='male',
            field=models.CharField(blank=True, choices=[('None', 'Не выбрано'), ('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], default=None, max_length=30, null=True),
        ),
    ]
