# Generated by Django 4.0.6 on 2022-11-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adressinfomodel',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='adressinfomodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
