# Generated by Django 4.0.6 on 2022-11-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_adressinfomodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adressinfomodel',
            name='address_coordinates',
        ),
        migrations.AddField(
            model_name='adressinfomodel',
            name='lat',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adressinfomodel',
            name='lng',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='AddressInfoModel',
        ),
    ]
