# Generated by Django 4.0.6 on 2022-12-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0120_alter_productoptionsmodel_product'),
        ('orders', '0032_ordermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel'),
        ),
    ]
