# Generated by Django 4.0.6 on 2022-09-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_delete_ratingstar_remove_reviewmodel_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='rating',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productmodel', verbose_name='product'),
            preserve_default=False,
        ),
    ]
