# Generated by Django 4.0.6 on 2022-09-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_remove_reviewmodel_product_productmodel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='rating',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.productmodel', verbose_name='product'),
            preserve_default=False,
        ),
    ]
