# Generated by Django 4.0.6 on 2022-09-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_alter_productmodel_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ['pk'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategorymodel',
            options={'ordering': ['pk'], 'verbose_name': 'subcategory', 'verbose_name_plural': 'subcategories'},
        ),
    ]
