# Generated by Django 4.0.6 on 2022-09-29 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondSubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_subcategory', models.CharField(max_length=200, verbose_name='second_subcategory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategorymodel', verbose_name='subcategory')),
            ],
            options={
                'verbose_name': 'second_subcategory',
                'verbose_name_plural': 'second_subcategories',
            },
        ),
    ]
