# Generated by Django 4.0.6 on 2022-09-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_secondsubcategorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondsubcategorymodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categorymodel', verbose_name='sub_cat'),
        ),
    ]
