# Generated by Django 4.0.6 on 2022-09-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_secondsubcategorymodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorymodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_category', to='products.categorymodel'),
        ),
        migrations.DeleteModel(
            name='SecondSubCategoryModel',
        ),
        migrations.DeleteModel(
            name='SubCategoryModel',
        ),
    ]
