# Generated by Django 4.0.6 on 2022-10-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_remove_categorymodel_parent_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('process', 'В процессе'), ('cancel', 'Заказ отменен'), ('delivery', 'Выполняется доставка'), ('success', 'Товар получен')], default='process', max_length=200, null=True),
        ),
    ]
