# Generated by Django 4.0.6 on 2022-10-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_alter_productmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
