# Generated by Django 4.0.6 on 2022-10-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0076_alter_reviewmodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormodel',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
    ]
