# Generated by Django 4.0.6 on 2022-10-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0078_rename_title_colormodel_color_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcustomnamemodel',
            old_name='custom_number',
            new_name='chars_number',
        ),
        migrations.RenameField(
            model_name='productcustomnamemodel',
            old_name='custom_name',
            new_name='chars_title',
        ),
        migrations.AlterField(
            model_name='productcustomnamemodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chars', to='products.productmodel', verbose_name='product'),
        ),
    ]
