# Generated by Django 4.0.6 on 2022-10-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0080_rename_number_productcharacteristicmodel_chars_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'ordering': ['pk'], 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
    ]
