# Generated by Django 4.0.6 on 2022-10-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0081_alter_reviewmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='current_chars',
            field=models.CharField(max_length=200, null=True, verbose_name='current_chars'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='current_numbers',
            field=models.CharField(max_length=212, null=True, verbose_name='current_numbers'),
        ),
    ]
