# Generated by Django 4.0.6 on 2022-10-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0082_productmodel_current_chars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='current_numbers',
        ),
    ]
