# Generated by Django 4.0.6 on 2022-10-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0084_rename_colors_productmodel_current_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='options',
            field=models.CharField(max_length=500, null=True, verbose_name='options'),
        ),
    ]
