# Generated by Django 4.0.6 on 2022-10-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0085_productmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='options',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='options'),
        ),
    ]
