# Generated by Django 4.0.6 on 2022-10-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0086_alter_productmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcustommodel',
            name='custom',
        ),
        migrations.RemoveField(
            model_name='productcustommodel',
            name='number',
        ),
        migrations.RemoveField(
            model_name='productcustommodel',
            name='price',
        ),
        migrations.AddField(
            model_name='productcustommodel',
            name='option',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='option'),
        ),
        migrations.AddField(
            model_name='productcustommodel',
            name='option1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='option1'),
        ),
        migrations.AddField(
            model_name='productcustommodel',
            name='option2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='option2'),
        ),
        migrations.AddField(
            model_name='productcustommodel',
            name='option3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='option3'),
        ),
        migrations.AddField(
            model_name='productcustommodel',
            name='option4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='option4'),
        ),
        migrations.AddField(
            model_name='productcustommodel',
            name='option5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='option5'),
        ),
        migrations.AddField(
            model_name='productcustommodel',
            name='option6',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='option6'),
        ),
    ]
