# Generated by Django 4.0.6 on 2022-10-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0087_remove_productcustommodel_custom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='current_chars',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='options',
        ),
    ]
