# Generated by Django 4.0.6 on 2022-10-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0088_remove_productmodel_current_chars_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCustomNameModel',
        ),
    ]
