# Generated by Django 4.0.6 on 2022-10-05 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0089_delete_productcustomnamemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcustommodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='options', to='products.productmodel', verbose_name='product'),
        ),
    ]
