# Generated by Django 4.0.6 on 2022-10-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0090_alter_productcustommodel_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributes',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='num',
        ),
        migrations.AddField(
            model_name='productattributes',
            name='option_number',
            field=models.PositiveIntegerField(null=True, verbose_name='option_number'),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='option_title',
            field=models.CharField(max_length=300, null=True, verbose_name='option_title'),
        ),
    ]
