# Generated by Django 4.0.6 on 2022-10-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0091_remove_productattributes_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributes',
            name='option_number',
            field=models.CharField(max_length=900, null=True, verbose_name='option_number'),
        ),
    ]
