# Generated by Django 4.0.6 on 2022-10-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0092_alter_productattributes_option_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributes',
            name='price',
        ),
    ]
