# Generated by Django 4.0.6 on 2022-10-05 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0093_remove_productattributes_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributes',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='products.productmodel', verbose_name='product'),
        ),
    ]
