# Generated by Django 4.0.6 on 2022-10-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0094_alter_productattributes_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributes',
            name='option_type',
            field=models.CharField(blank=True, default='default', max_length=90, null=True),
        ),
    ]
