# Generated by Django 4.0.6 on 2022-10-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0095_productattributes_option_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormodel',
            name='color_type',
            field=models.CharField(default='color', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ProductCustomModel',
        ),
    ]
