# Generated by Django 4.0.6 on 2022-10-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0096_colormodel_color_type_delete_productcustommodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='condition',
            field=models.CharField(blank=True, choices=[('NEW', 'Новый'), ('USED', 'Б/у')], max_length=20, null=True, verbose_name='condition'),
        ),
    ]
