# Generated by Django 4.0.6 on 2022-10-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0097_productmodel_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='current_color',
            new_name='сolors',
        ),
    ]
