# Generated by Django 4.0.6 on 2022-10-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0101_alter_reviewmodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
