# Generated by Django 4.0.6 on 2022-10-14 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0104_alter_reviewimagemodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='reviewimagemodel',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.reviewmodel'),
        ),
    ]
