# Generated by Django 4.0.6 on 2022-10-14 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0105_remove_reviewmodel_image_reviewimagemodel_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimagemodel',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.reviewmodel'),
        ),
    ]
