# Generated by Django 4.0.6 on 2022-10-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0106_alter_reviewimagemodel_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
    ]
