# Generated by Django 4.0.6 on 2022-10-14 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0107_alter_reviewmodel_email_alter_reviewmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimagemodel',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.reviewmodel'),
        ),
    ]
