# Generated by Django 4.0.6 on 2022-10-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0108_alter_reviewimagemodel_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='review_count',
        ),
    ]
