# Generated by Django 4.0.6 on 2022-10-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0109_remove_reviewmodel_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimagemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at'),
        ),
    ]
