# Generated by Django 4.0.6 on 2022-10-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0110_reviewimagemodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimagemodel',
            name='review',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='products.reviewimagemodel'),
        ),
        migrations.AlterField(
            model_name='reviewimagemodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='form_images', verbose_name='image'),
        ),
    ]
