# Generated by Django 4.0.6 on 2022-10-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0111_remove_reviewimagemodel_review_reviewmodel_images_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'ordering': ['-pk'], 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
    ]
