# Generated by Django 4.0.6 on 2022-10-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0116_alter_currentproductoptionsmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentproductoptionsmodel',
            name='current_options_number',
            field=models.CharField(max_length=300, verbose_name='current_options_number'),
        ),
        migrations.AlterField(
            model_name='currentproductoptionsmodel',
            name='current_options_title',
            field=models.CharField(max_length=300, verbose_name='current_options_title'),
        ),
    ]
