# Generated by Django 4.0.6 on 2022-12-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0120_alter_productoptionsmodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='variation',
            field=models.CharField(max_length=400, null=True, verbose_name='variation'),
        ),
    ]
